export enum ChannelEvents  {
  CHAT_CONVERSATION_CREATED = 'CHAT_CONVERSATION_CREATED',
  CHAT_CONVERSATION_UPDATED = 'CHAT_CONVERSATION_UPDATED',
  CHAT_MESSAGE_CREATED = 'CHAT_MESSAGE_CREATED',
  CHAT_MESSAGE_UPDATED = 'CHAT_MESSAGE_UPDATED',
  CHAT_MESSAGE_DELETED = 'CHAT_MESSAGE_DELETED',
}
