# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

### file validator
# https://bitbucket-pipelines.prod.public.atl-paas.net/validator
###

### file configure
# https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
#
image: node:10.5.0

pipelines:
  default:
    - step:
        caches:
          - node
    - step:
        name: Global tasks
        script:
          - echo "This script runs on all branches"

  branches:
    development:
      - step:
          name: Installation
          script:
            - yarn
            - yarn add global @angular/cli@1.7.4
      - step:
          name: Building
          script:
            - ng build --prod --env test --app portal

#  default:
#    - step:
#        caches:
#          - node
#        script: # Modify the commands below to build your repository.
#          - npm install
