# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.5.0

pipelines:
  default:
    - step:
        name: Global tasks
        script:
          - echo "This script runs on all branches"
  branches:
    development:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install
      - step:
          name: Building
          script:
            ng build --prod --app portal

#  default:
#    - step:
#        caches:
#          - node
#        script: # Modify the commands below to build your repository.
#          - npm install
