export const CONVERSATION_MANAGE = 'CONVERSATION_MANAGE';
export const CONVERSATION_UPDATE = 'CONVERSATION_UPDATE';
export const CONVERSATION_EDIT = 'CONVERSATION_EDIT';
export const CONVERSATION_CREATE = 'CONVERSATION_CREATE';
export const CONVERSATION_DELETE = 'CONVERSATION_DELETE';
