export const NOTIFICATION_MARK_AS_READ = 'NOTIFICATION_MARK_AS_READ';
export const NOTIFICATION_MARK_ALL_AS_READ = 'NOTIFICATION_MARK_ALL_AS_READ';
export const NOTIFICATION_MARK_ALL_AS_UNREAD = 'NOTIFICATION_MARK_ALL_AS_UNREAD';
export const NOTIFICATION_INCREASE_COUNT = 'NOTIFICATION_INCREASE_COUNT';
export const NOTIFICATION_UPDATE_COUNT = 'NOTIFICATION_UPDATE_COUNT';
